app = "app-fsjkvaxr"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  # The DATABASE_URL will be set as a secret

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "cd /app && python -m pip install -r requirements.txt"

[processes]
  app = "cd /app && gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
