app = "app-fsjkvaxr"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  DATABASE_URL = "postgresql://doadmin:AVNS_ifzweLn1iD8jj3kBsZf@bauen-db-do-user-20046124-0.d.db.ondigitalocean.com:25060/timekeeper"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "cd /app && python -m pip install -r requirements.txt"

[processes]
  app = "cd /app && python -m uvicorn main:app --host 0.0.0.0 --port 8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
